# this file is used to generate a list of projects that
# should be showcases on my website.

# read more here: https://mosaic.luxass.dev
# schema can be found here: https://mosaic.luxass.dev/json-schema.json

[project]
name = "lesetid"
version = true

[npm]
enabled = true
downloads = true

[website]
enabled = true

[workspace]
enabled = true
ignores = [
  "examples/*",
  "www"
]

[workspace.overrides.vscode-reading-time]
project = { ignore = true }

[workspace.overrides.lesetid]
project = { priority = 20 }
