---
# Commands to start on workspace startup
tasks:
  - before: |
      # Get latest pnpm version, in case the custom docker image was not updated
      # Until this issue gets resolved - https://github.com/gitpod-io/gitpod/issues/12551
      curl -fsSL https://get.pnpm.io/install.sh | SHELL=`which bash` bash -
    init: |
      pnpm install
      pnpm run build
    command: |
      .gitpod/gitpod-setup.sh

vscode:
  extensions:
    - astro-build.astro-vscode
    - luxass.tsup-problem-matchers
    - vue.vscode-typescript-vue-plugin
    - vue.volar
    - nuxtr.nuxtr-vscode
    - dbaeumer.vscode-eslint
ports:
  - port: 3000
    onOpen: open-preview
  - port: 3001
    onOpen: ignore
  - port: 3002
    onOpen: ignore
  - port: 4321
    onOpen: ignore
