packages:
  - www
  - packages/*
  - examples/*
  - tooling/*

catalogs:
  linting:
    "@luxass/eslint-config": ^5.1.1
    "eslint": ^9.32.0
    "eslint-plugin-format": ^1.0.1
    "@unocss/eslint-plugin": ^66.3.3
    "astro-eslint-parser": ^1.2.2
    "eslint-plugin-astro": ^1.3.1
    "prettier-plugin-astro": ^0.14.1

  testing:
    vitest: ^3.2.4
    "@vitest/coverage-v8": ^3.2.4

  monorepo:
    "@changesets/changelog-github": ^0.5.1
    "@changesets/cli": ^2.29.5
    tsdown: ^0.13.0
    turbo: ^2.5.5
    typescript: ^5.8.3
    volapyk: ^1.6.3
    publint: ^0.3.12

  lesetid:
    "hastscript": ^9.0.1
    "mdast-util-to-string": ^4.0.0
    "unist-util-visit": ^5.0.0
    "unified": ^11.0.5
    "vfile": 6.0.3
    "@types/mdast": ^4.0.4
    "@types/node": ^22.0.0

  remark-lesetid:
    "hastscript": ^9.0.1
    "mdast-util-to-string": ^4.0.0
    "unist-util-visit": ^5.0.0
    "unified": ^11.0.5
    "vfile": 6.0.3
    "@types/mdast": ^4.0.4
    "@types/node": ^22.0.0

  www:
    "@iconify-json/logos": ^1.2.5
    "@iconify-json/ph": ^1.2.2
    "astro": ^5.12.3
    "astro-icon": ^1.1.5
    "zod": ^3.25.76
    "@astrojs/check": ^0.9.4
    "@unocss/reset": ^66.3.3
    "unocss": ^66.3.3
    "@astrojs/mdx": ^4.3.1
    "@astrojs/rss": ^4.0.12
    "@astrojs/sitemap": ^3.4.1
    "@astrojs/cloudflare": ^12.6.0
    wrangler: ^4.26.0

  example:
    "classnames": ^2.5.1
    "date-fns": ^4.1.0
    "gray-matter": ^4.0.3
    "next": ^15.4.4
    "react": ^19.1.0
    "react-dom": ^19.1.0
    "remark-html": ^16.0.1
    "remark": ^15.0.1
    "@tailwindcss/postcss": ^4.1.11
    "@types/react": ^19.1.8
    "@types/react-dom": ^19.1.6
    "postcss": ^8.5.6
    "tailwindcss": ^4.1.11

onlyBuiltDependencies:
  - esbuild
