packages:
  - www
  - packages/*
  - examples/*
catalogs:
  prod:
    "@iconify-json/logos": ^1.2.4
    "@iconify-json/ph": ^1.2.2
    "astro": ^5.5.5
    "astro-icon": ^1.1.5
    "hastscript": ^9.0.1
    "mdast-util-to-string": ^4.0.0
    "unist-util-visit": ^5.0.0
    "zod": ^3.24.2
  dev:
    "unified": ^11.0.5
    "vfile": 6.0.3
    "@astrojs/check": ^0.9.4
    "@changesets/changelog-github": ^0.5.1
    "@changesets/cli": ^2.28.1
    "@luxass/eslint-config": ^4.18.1
    "@manypkg/cli": ^0.23.0
    "@types/mdast": ^4.0.4
    "@types/node": ^22.0.0
    "@unocss/eslint-plugin": ^66.0.0
    "@unocss/reset": ^66.0.0
    "astro-eslint-parser": ^1.2.2
    "eslint": ^9.23.0
    "eslint-plugin-astro": ^1.3.1
    "eslint-plugin-format": ^1.0.1
    "prettier-plugin-astro": ^0.14.1
    "tsup": ^8.4.0
    "turbo": ^2.4.4
    "typescript": ^5.8.2
    "unocss": ^66.0.0
    "vitest": ^3.0.9
    "volapyk": ^1.6.3
  example:
    "classnames": ^2.5.1
    "date-fns": ^4.1.0
    "gray-matter": ^4.0.3
    "next": ^15.2.4
    "react": ^19.1.0
    "react-dom": ^19.1.0
    "remark-html": ^16.0.1
    "remark": ^15.0.1
    "@tailwindcss/postcss": ^4.0.17
    "@types/react": ^19.0.12
    "@types/react-dom": ^19.0.4
    "postcss": ^8.5.3
    "tailwindcss": ^4.0.4
    "@astrojs/mdx": ^4.2.2
    "@astrojs/rss": ^4.0.11
    "@astrojs/sitemap": ^3.3.0

onlyBuiltDependencies:
  - esbuild
