packages:
  - www
  - packages/*
  - examples/*
  - tooling/*

catalogs:
  linting:
    "@luxass/eslint-config": ^5.3.2
    "eslint": ^9.35.0
    "eslint-plugin-format": ^1.0.1
    "@unocss/eslint-plugin": ^66.5.1
    "astro-eslint-parser": ^1.2.2
    "eslint-plugin-astro": ^1.3.1
    "prettier-plugin-astro": ^0.14.1

  testing:
    vitest: ^3.2.4
    "@vitest/coverage-v8": ^3.2.4

  monorepo:
    "@changesets/changelog-github": ^0.5.1
    "@changesets/cli": ^2.29.7
    tsdown: ^0.15.1
    turbo: ^2.5.6
    typescript: ^5.9.2
    volapyk: ^2.0.0
    publint: ^0.3.12

  lesetid:
    "hastscript": ^9.0.1
    "mdast-util-to-string": ^4.0.0
    "unist-util-visit": ^5.0.0
    "unified": ^11.0.5
    "vfile": 6.0.3
    "@types/mdast": ^4.0.4
    "@types/node": ^22.18.1

  remark-lesetid:
    "hastscript": ^9.0.1
    "mdast-util-to-string": ^4.0.0
    "unist-util-visit": ^5.0.0
    "unified": ^11.0.5
    "vfile": 6.0.3
    "@types/mdast": ^4.0.4
    "@types/node": ^22.18.1

  www:
    "@iconify-json/logos": ^1.2.9
    "@iconify-json/ph": ^1.2.2
    "astro": ^5.13.7
    "astro-icon": ^1.1.5
    "zod": ^3.25.76
    "@astrojs/check": ^0.9.4
    "@unocss/reset": ^66.5.1
    "unocss": ^66.5.1
    "@astrojs/mdx": ^4.3.5
    "@astrojs/rss": ^4.0.12
    "@astrojs/sitemap": ^3.5.1
    "@astrojs/cloudflare": ^12.6.8
    wrangler: ^4.36.0

  example:
    "classnames": ^2.5.1
    "date-fns": ^4.1.0
    "gray-matter": ^4.0.3
    "next": ^15.5.3
    "react": ^19.1.1
    "react-dom": ^19.1.1
    "remark-html": ^16.0.1
    "remark": ^15.0.1
    "@tailwindcss/postcss": ^4.1.13
    "@types/react": ^19.1.13
    "@types/react-dom": ^19.1.9
    "postcss": ^8.5.6
    "tailwindcss": ^4.1.13

onlyBuiltDependencies:
  - esbuild
