packages:
  - www
  - packages/*
  - examples/*
  - tooling/*

catalogs:
  linting:
    "@luxass/eslint-config": 6.0.3
    "eslint": 9.39.1
    "eslint-plugin-format": 1.1.0
    "@unocss/eslint-plugin": 66.5.10
    "astro-eslint-parser": 1.2.2
    "eslint-plugin-astro": 1.5.0
    "prettier-plugin-astro": 0.14.1

  testing:
    vitest: 4.0.15
    "@vitest/coverage-v8": 4.0.15

  monorepo:
    "@changesets/changelog-github": 0.5.2
    "@changesets/cli": 2.29.8
    tsdown: 0.17.2
    turbo: 2.6.3
    typescript: 5.9.3
    volapyk: 2.1.0
    publint: 0.3.16

  lesetid:
    "hastscript": 9.0.1
    "mdast-util-to-string": 4.0.0
    "unist-util-visit": 5.0.0
    "unified": 11.0.5
    "vfile": 6.0.3
    "@types/mdast": 4.0.4
    "@types/node": 24.10.3

  remark-lesetid:
    "hastscript": 9.0.1
    "mdast-util-to-string": 4.0.0
    "unist-util-visit": 5.0.0
    "unified": 11.0.5
    "vfile": 6.0.3
    "@types/mdast": 4.0.4
    "@types/node": 24.10.3

  www:
    "@iconify-json/logos": 1.2.10
    "@iconify-json/ph": 1.2.2
    "astro": 5.16.5
    "astro-icon": 1.1.5
    "zod": 3.25.76
    "@astrojs/check": 0.9.6
    "@unocss/reset": 66.5.10
    "unocss": 66.5.10
    "@astrojs/mdx": 4.3.13
    "@astrojs/rss": 4.0.14
    "@astrojs/sitemap": 3.6.0
    "@astrojs/cloudflare": 12.6.12
    wrangler: 4.54.0

  example:
    "classnames": 2.5.1
    "date-fns": 4.1.0
    "gray-matter": 4.0.3
    "next": 16.0.10
    "react": 19.2.3
    "react-dom": 19.2.3
    "remark-html": 16.0.1
    "remark": 15.0.1
    "@tailwindcss/postcss": 4.1.18
    "@types/react": 19.2.7
    "@types/react-dom": 19.2.3
    "postcss": 8.5.6
    "tailwindcss": 4.1.18

onlyBuiltDependencies:
  - esbuild
