packages:
  - apps/*
  - packages/*
  - examples/*
catalog:
  "@astrojs/check": ^0.9.4
  "@astrojs/mdx": ^4.0.2
  "@astrojs/netlify": ^6.0.0
  "@astrojs/sitemap": ^3.2.1
  "@astrojs/solid-js": ^5.0.0
  "@astrojs/tailwind": ^5.1.3
  "@changesets/changelog-github": ^0.5.0
  "@changesets/cli": ^2.27.10
  "@eslint-react/eslint-plugin": ^1.19.0
  "@iconify-json/carbon": ^1.2.4
  "@iconify-json/logos": ^1.2.3
  "@iconify-json/lucide": ^1.2.18
  "@iconify-json/mdi": ^1.2.1
  "@iconify-json/octicon": 1.2.2
  "@iconify-json/tabler": ^1.2.11
  "@iconify/tailwind": 1.2.0
  "@luxass/eslint-config": ^4.14.0
  "@next/mdx": ^15.1.0
  "@nuxt/content": ^2.13.4
  "@nuxt/devtools": ^1.6.4
  "@nuxt/image": ^1.8.1
  "@nuxtjs/color-mode": ^3.5.2
  "@nuxtjs/fontaine": ^0.4.4
  "@nuxtjs/tailwindcss": ^6.12.2
  "@svgr/core": ^8.1.0
  "@svgr/plugin-jsx": ^8.1.0
  "@tailwindcss/typography": ^0.5.15
  "@types/hast": ^3.0.4
  "@types/mdast": ^4.0.4
  "@types/node": ^18.19.68
  "@types/react": ^18.3.16
  "@types/react-dom": ^18.3.5
  "@vueuse/core": ^12.0.0
  "@vueuse/nuxt": ^12.0.0
  astro: ^5.2.5
  astro-icon: ^1.1.4
  autoprefixer: ^10.4.20
  class-variance-authority: ^0.7.1
  eslint: ^9.19.0
  eslint-plugin-astro: ^1.3.1
  eslint-plugin-format: ^0.1.3
  eslint-plugin-react-hooks: ^5.1.0
  eslint-plugin-react-refresh: ^0.4.16
  eslint-plugin-solid: ^0.14.5
  eslint-plugin-tailwindcss: ^3.17.5
  gray-matter: ^4.0.3
  hastscript: ^9.0.0
  mdast-util-directive: ^3.0.0
  mdast-util-to-string: ^4.0.0
  next-mdx-remote: ^5.0.0
  nuxt: ^3.14.1592
  nuxt-icon: ^0.6.10
  postcss: ^8.4.49
  prettier-plugin-astro: ^0.14.1
  react: ^19.0.0
  react-dom: ^19.0.0
  rehype-autolink-headings: ^7.1.0
  rehype-external-links: ^3.0.0
  rehype-pretty-code: ^0.14.0
  rehype-slug: ^6.0.0
  remark: ^15.0.1
  remark-directive: ^3.0.0
  remark-gfm: ^4.0.0
  shiki: ^1.24.2
  sitemap: ^8.0.0
  solid-js: ^1.9.3
  tailwind-merge: ^2.5.5
  tailwindcss: ^3.4.16
  tsup: ^8.3.6
  turbo: ^2.4.0
  typescript: ^5.7.3
  unified: ^11.0.5
  unist-util-remove: ^4.0.0
  unist-util-visit: ^5.0.0
  unplugin-icons: ^0.21.0
  valibot: ^0.42.1
  vfile: 6.0.3
  vitest: ^3.0.5
  volapyk: ^1.6.2
  vue: ^3.5.13
  vue-router: ^4.5.0
  vue-tsc: ^2.2.0
  zod: ^3.24.1
