name: GitHub Actions Security Analysis

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - ".github/workflows/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"

permissions: {}

jobs:
  zizmor:
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: luxass/shared-workflows/.github/workflows/ci-security.yaml@495f6427f288e78bddfca573876da1357549379d # v0.8.3
    with:
      zizmor-version: v1.23.1
