name: CI

# You can leverage Vercel Remote Caching with Turbo to speed up your builds
# @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Setup node
        uses: actions/setup-node@v4.1.0
        with:
          node-version: lts/*

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm turbo build --filter "./packages/*"

      - name: Lint
        run: pnpm turbo lint --filter "./packages/*"

      - name: Typecheck
        run: pnpm turbo typecheck --filter "./packages/*"

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [20, 18]
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
      fail-fast: false

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node ${{ matrix.node }}
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build --filter "./packages/*"

      - name: Test
        run: pnpm test --filter "./packages/*"
