name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

permissions: {}

jobs:
  ci:
    permissions:
      contents: read
    uses: luxass/shared-workflows/.github/workflows/ci.yaml@495f6427f288e78bddfca573876da1357549379d # v0.8.3

  test:
    permissions:
      contents: read
    uses: luxass/shared-workflows/.github/workflows/test.yaml@495f6427f288e78bddfca573876da1357549379d # v0.8.3
