name: Examples CI

on:
  push:
    branches:
      - main
    paths: 
      - "examples/**/.lesetid/**"

env:
  FORCE_COLOR: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Corepack enable
        run: corepack enable

      - name: Setup PNPM
        uses: pnpm/action-setup@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Update README Links
        run: pnpx tsx ./scripts/update-example-links.ts

      - name: Commit README Links
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update example links"
          branch: ${{ github.head_ref }}
