name: Release
on:
  push:
    branches:
      - main

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Changelog PR or Release
    if: ${{ github.repository == 'luxass/lesetid' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v4.0.0

      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4.0.2
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install deps (with cache)
        run: pnpm install

      - name: Check packages for common errors
        run: pnpm turbo --filter "./packages/*" build lint test typecheck

      - name: Create Release
        id: changeset
        uses: changesets/action@v1.4.7
        with:
          commit: "chore(release): 📦 version packages"
          title: "chore(release): 📦  version packages"
          publish: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      # Changeset has some issues with pnpm so we sync it up manually
      - name: Sync lockfile if necessary
        if: steps.changeset.outputs.hasChangesets == 'true'
        run: |
          git checkout changeset-release/main
          pnpm install --no-frozen-lockfile
          git add .
          git commit -m "chore(release): 📦 sync lockfile"
          git push origin changeset-release/main
